#+OPTIONS: toc:nil 
#+TITLE: Proyecto Final
#+OPTIONS: author:nil 
#+LANGUAGE: es


* Objetivo General del Proyecto 

Que los alumnos se familiaricen y lleven a la práctica los aprendizajes obtenidos durante el curso de Análisis Aplicado. 

* Proyecto
Investigar una aplicación donde las metodologías implementadas en el curso tengan cabida y hayan ayudado a resolver algún problema más grande dentro de la optimización o la vida real. Deben subir su propuesta dentro al archivo:  ~Proyecto/<nombre del equipo>/Propuesta.<md|org>~ para el día *2021-04-26* antes de la clase, para poderlas discutir. 

Además de investigar el tema y dar una explicación del tema, tienen que condensar un problema de optimización que sus algoritmos implementados en el semestre, puedan resolver. 

Hacer una presentación en formato libre de todo lo investigado y aprendizajes encontrados con las metodologías. Se hará día de presentaciones el día May-12.
* Organización proyecto
Ojo que dentro de la carpeta  ~Proyecto/<nombre del equipo>/~ deberán subir todo el código que hayan adaptado, implementado o reescrito para mostrar todo el trabajo hecho por el equipo. Para que quede registrado, deberá ser entregado también via /pull request/. 
* Formato
Se hará una presentación a final del semestre al estilo poster de conferencia, (no es necesario que impriman nada, sólo que presenten planteamiento, relación con la temática del curso y resultados con los algoritmos implementados).

* Fechas Importantes
- Fecha límite entrega de propuestas: *2021-04-26*
- Fecha de /Show and Tell/ : *2021-05-12*
* Equipos
Favor de introducir, en el formato que está aquí, los integrantes y las temáticas que van a tocar
|--------+------------------------------------+----------------------------------|
| Equipo | Temática                           | Integrantes                      |
|--------+------------------------------------+----------------------------------|
|      1 | Optimizando el desempeño académico | Alonso Martinez, 172255          |
|        |                                    | Julieta Rivero, 170454           |
|        |                                    | Rebeca Angulo, 175311            |
|--------+------------------------------------+----------------------------------|
|      2 | Ubicación de policías/alumbrado    | María de la Luz Vizcaíno, 157045 |
|        | público en la CDMX                 | Sebastián Martínez, 176357       |
|        |                                    | Álvaro Acedo, 174052             |                 
|        |                                    | Iván (CU pendiente)              |
|        |                                    | José Hurtado (CU Pendiente)      |
|--------+------------------------------------+----------------------------------|
|      3 | Otro Nuevo Tema                    | Integrante 1, 000110022          |
|        |                                    | Integrante 2, 000110022          |
|        |                                    | Integrante 3, 000110022          |
|        |                                    | Integrante 4, 000110022          |
|        |                                    | Integrante 5, 000110022          |
|--------+------------------------------------+----------------------------------|
